---
- name: Set Admin State to Up
  hosts: all
  gather_facts: false
  connection: netconf
  tasks:
  
    - name: Admins up Arista interface
      arista.eos.eos_interfaces:
        config:
        - name: "{{ affected_interface }}"
          enabled: true
      when: "device_os == 'eos'"

    - name: Admins up Cisco interface
      cisco.nxos.nxos_interfaces:
        config:
        - name: "{{ affected_interface }}"
          enabled: true
      when: "device_os == 'nxos'"
