---
- name: Set Admin State to Up
  hosts: all
  gather_facts: false
  connection: network_cli
  tasks:
  
    - name: Admins up Arista interface
      arista.eos.eos_interfaces:
        config:
        - name: "{{ affected_interface }}"
          enabled: true
        state: replaced
      when: "ansible_network_os==eos"

    - name: Merge provided configuration with device configuration
      cisco.nxos.nxos_interfaces:
        config:
        - name: Ethernet1/1
          enabled: true
        state: replaced
      when: ansible_network_os == nxos
