---

- name: Port State Event from Arista

  hosts: all

  sources:
   - ansible.eda.kafka:
       host: 172.16.1.135
       port: 9092
       topic: telegraf

  rules:
   - name: Test
     condition: event.fields.admin_status == "DOWN"
     action:
       run_job_template:
         name: EDA_Admin
