---
- name: Port State Event from network
  hosts: all
  sources:
   - ansible.eda.kafka:
       host: 172.16.1.135
       port: 9092
       topic: telegraf
  rules:
   - name: Test
     condition: event.body.fields.admin_status == "DOWN"
     action:
       run_job_template:
         organization: "Default"
         name: "EDA_Admin"
         post_events: true
         job_args:
           extra_vars:
             limit: ansible_eda.event.body.tags.source